version: '3.5'
services:
  webserver1:
    image: httpd:latest
    ports:
      - "8555"
    volumes:
      - ./contents:/usr/local/apache2/htdocs

  webserver2:
    image: httpd:latest
    ports:
      - "8555"
    volumes:
      - ./contents2:/usr/local/apache2/htdocs

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
~                                                                                                                       ~                                                         
